module.exports = {
  CONTAINER_CREATED: 'CONTAINER_CREATED',
  LOADED_ON_SHIP: 'LOADED_ON_SHIP',
  LOCATION_UPDATED: 'LOCATION_UPDATED',
  TEMPERATURE_RECORDED: 'TEMPERATURE_RECORDED',
  TEMPERATURE_SPIKE: 'TEMPERATURE_SPIKE',
  ARRIVED_AT_PORT: 'ARRIVED_AT_PORT',
  UNLOADED: 'UNLOADED',
  DELIVERY_COMPLETED: 'DELIVERY_COMPLETED',
};
